config_file = "config.toml"
role = "node"
node_name = "node222"
node_ip = "127.0.0.1"
mount_path = "/tmp/datenlord_data_dir"
kv_server_list = [
    "127.0.0.1:2379"
]
server_port = 8800
scheduler_extender_port = 12345

[storage]
storage_type = "fs"
block_size = 524288
fs_storage_root = "/tmp/datenlord_backend"

[storage.memory_cache_config]
capacity = 8589934592
command_queue_limit = 1000
write_back = false
soft_limit = "3,5"

[storage.s3_storage_config]
endpoint_url = ""
access_key_id = ""
secret_access_key = ""
bucket_name = ""

[csi_config]
endpoint = "unix:///tmp/node.sock "
driver_name = "io.datenlord.csi.plugin"
worker_port = 9001
